### ISSUE TITLE
TypeError: test_failure() got an unexpected keyword argument 'stdout'

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/zope.testrunner#103]
I see this now when testing Plone 6.0 (development version). See a [Jenkins job](https://jenkins.plone.org/job/plone-6.0-python-3.7/18/console) and scroll to the end:

```
Traceback (most recent call last):
  File "bin/test", line 390, in <module>
    '--test-path', '/home/jenkins/.buildout/eggs/cp37m/repoze.xmliter-0.6-py3.7.egg',
  File "/home/jenkins/.buildout/eggs/cp37m/collective.xmltestreport-2.0.1-py3.7.egg/collective/xmltestreport/runner.py", line 66, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/.buildout/eggs/cp37m/collective.xmltestreport-2.0.1-py3.7.egg/collective/xmltestreport/runner.py", line 79, in run_internal
    runner.run()
  File "/home/jenkins/.buildout/eggs/cp37m/zope.testrunner-5.1-py3.7.egg/zope/testrunner/runner.py", line 191, in run
    self.run_tests()
  File "/home/jenkins/.buildout/eggs/cp37m/zope.testrunner-5.1-py3.7.egg/zope/testrunner/runner.py", line 293, in run_tests
    self.skipped, self.import_errors)
  File "/home/jenkins/.buildout/eggs/cp37m/zope.testrunner-5.1-py3.7.egg/zope/testrunner/runner.py", line 474, in run_layer
    import_errors)
  File "/home/jenkins/.buildout/eggs/cp37m/zope.testrunner-5.1-py3.7.egg/zope/testrunner/runner.py", line 396, in run_tests
    test(result)
  File "/srv/python3.7/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/srv/python3.7/lib/python3.7/unittest/case.py", line 636, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/srv/python3.7/lib/python3.7/unittest/case.py", line 564, in _feedErrorsToResult
    result.addFailure(test, exc_info)
  File "/home/jenkins/.buildout/eggs/cp37m/zope.testrunner-5.1-py3.7.egg/zope/testrunner/runner.py", line 954, in addFailure
    stdout=stdout, stderr=stderr)
TypeError: test_failure() got an unexpected keyword argument 'stdout'
```

I have not dived into this yet. What probably influences this error, is that we use [`collective.xmltestreport`](https://github.com/collective/collective.xmltestreport) and use this when calling `bin/test --xml`. It might do stuff with `stdout` that `zope.testrunner` does not expect.

**Comment by mgedmin** [comment]
This smells like an incompatibility of collective.xmltestreport with newer versions of zope.testrunner.

Commit ad054c8447b0875c14df5703ef6837f54ca0dbb2 introduced a new feature and added those new keyword arguments to the OutputFormatter.test_failure() method.  It was released in zope.testrunner 5.1.  Downgrading to an older zope.testrunner might be the easiest temporary workaround.

**Comment by mauritsvanrees** [comment]
Thanks, that is indeed the problem. I am creating a PR for `collective.xmltestreport` now so it should work with older and newer versions of `zope.testrunner`.

**Comment by mgedmin** [comment]
For the record, I would accept a PR to this repo adding Travis jobs running collective.xmltestreport's test suite with the current zope.testrunner snapshot.

(Ideally zope.testrunner would support generating junit xml files natively, so collective.xmltestreport or complicated subunit pipe jobs wouldn't be necessary.)

**Comment by mauritsvanrees** [comment]
Thanks. But that would require us to write some tests in `collective.xmltestreport` first. :-)

Maybe the two can be merged indeed.
Apparently I am the [biggest contributor](https://github.com/collective/collective.xmltestreport/graphs/contributors) to that package, but in my mind I just fix a bug every now and then, so I hardly now what it does...
