### ISSUE TITLE
subunit tests started failing recently

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.testrunner#125]
With no changes to zope.testrunner's codebase itself, weekly GitHub Actions builds started failing recently.  Example failure:  https://github.com/zopefoundation/zope.testrunner/runs/3097229321?check_suite_focus=true

The failures all involve subunit.

**Comment by cjwatson** [comment]
Dropping back to `testtools==2.4.0` works around this.  Not yet sure what's gone wrong here.

**Comment by cjwatson** [comment]
This is also visible in the subunit test suite when pointing it at testtools 2.5.0, although I had to mess about a bit to get it set up (the GHA tests fail for some unrelated reasons involving Automake, and the subunit tests need to be fixed to `import six` from the right place):

```
$ SHELL_SHARE=./shell/share/ PYTHONPATH=/home/cjwatson/src/python/testtools:/home/cjwatson/src/python/subunit/python:/home/cjwatson/src/python/subunit python3 -m testtools.run all_tests.test_suite
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'testtools.run' found in sys.modules after import of package 'testtools', but prior to execution of 'testtools.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Tests running...
======================================================================
FAIL: subunit.tests.test_test_protocol.TestTestProtocolClient.test_add_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cjwatson/src/python/subunit/python/subunit/tests/test_test_protocol.py", line 1283, in test_add_error
    self.assertEqual(
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 393, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = b'''\
error: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [
testtools.testresult.real._StringException: phwoar crikey
]
'''
actual    = b'''\
error: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [
Traceback (most recent call last):
testtools.testresult.real._StringException: phwoar crikey
]
'''
======================================================================
FAIL: subunit.tests.test_test_protocol.TestTestProtocolClient.test_add_error_details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cjwatson/src/python/subunit/python/subunit/tests/test_test_protocol.py", line 1293, in test_add_error_details
    self.assertThat([
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: b'error: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;language=python,charset=utf8\ntraceback\n34\r\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n' not in [b'error: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;charset=utf8,language=python\ntraceback\n57\r\nTraceback (most recent call last):\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n', b'error: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;language=python,charset=utf8\ntraceback\n57\r\nTraceback (most recent call last):\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n']
======================================================================
FAIL: subunit.tests.test_test_protocol.TestTestProtocolClient.test_add_expected_failure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cjwatson/src/python/subunit/python/subunit/tests/test_test_protocol.py", line 1315, in test_add_expected_failure
    self.assertEqual(
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 393, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = b'''\
xfail: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [
testtools.testresult.real._StringException: phwoar crikey
]
'''
actual    = b'''\
xfail: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [
Traceback (most recent call last):
testtools.testresult.real._StringException: phwoar crikey
]
'''
======================================================================
FAIL: subunit.tests.test_test_protocol.TestTestProtocolClient.test_add_expected_failure_details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cjwatson/src/python/subunit/python/subunit/tests/test_test_protocol.py", line 1325, in test_add_expected_failure_details
    self.assertThat([
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: b'xfail: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;language=python,charset=utf8\ntraceback\n34\r\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n' not in [b'xfail: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;charset=utf8,language=python\ntraceback\n57\r\nTraceback (most recent call last):\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n', b'xfail: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;language=python,charset=utf8\ntraceback\n57\r\nTraceback (most recent call last):\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n']
======================================================================
FAIL: subunit.tests.test_test_protocol.TestTestProtocolClient.test_add_failure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cjwatson/src/python/subunit/python/subunit/tests/test_test_protocol.py", line 1252, in test_add_failure
    self.assertEqual(
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 393, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = b'''\
failure: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [
testtools.testresult.real._StringException: boo qux
]
'''
actual    = b'''\
failure: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [
Traceback (most recent call last):
testtools.testresult.real._StringException: boo qux
]
'''
======================================================================
FAIL: subunit.tests.test_test_protocol.TestTestProtocolClient.test_add_failure_details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cjwatson/src/python/subunit/python/subunit/tests/test_test_protocol.py", line 1261, in test_add_failure_details
    self.assertThat([
  File "/home/cjwatson/src/python/testtools/testtools/testcase.py", line 480, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: b'failure: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;language=python,charset=utf8\ntraceback\n34\r\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n' not in [b'failure: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;charset=utf8,language=python\ntraceback\n57\r\nTraceback (most recent call last):\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n', b'failure: subunit.tests.test_test_protocol.TestTestProtocolClient.test_start_test [ multipart\nContent-Type: text/plain\nsomething\nF\r\nserialised\nform0\r\nContent-Type: text/x-traceback;language=python,charset=utf8\ntraceback\n57\r\nTraceback (most recent call last):\ntesttools.testresult.real._StringException: boo qux\n0\r\n]\n']

Ran 532 tests in 1.962s
FAILED (failures=6)
```

**Comment by cjwatson** [comment]
OK, this is because testtools 2.5.0 switched from traceback2 to the standard library's traceback, which includes the fix for https://bugs.python.org/issue24695.  In the failing test cases, there is in fact no exception traceback, so it's correct to omit the traceback header; that is, this was a regression in traceback2 to begin with.

I think we should just adjust the tests to tolerate either the old or the new behaviour here.
