### ISSUE TITLE
The test runner hides errors in non-Unicode locales

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.testrunner#18]
A build [failed](http://winbot.zope.org/builders/z3c.form_py_265_32/builds/-1/steps/test/logs/stdout) on winbot recently, but we can't see why, because the error reporting failed with a UnicodeError:

```
Traceback (most recent call last):
  File "c:\buildslave\z3c.form\build\bin\test-script.py", line 68, in <module>
    '--test-path', 'c:\\buildslave\\z3c.form\\build\\src',
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\__init__.py", line 27, in run
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd)
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\__init__.py", line 44, in run_internal
    runner.run()
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\runner.py", line 160, in run
    self.run_tests()
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\runner.py", line 242, in run_tests
    self.skipped, self.import_errors)
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\runner.py", line 411, in run_layer
    import_errors)
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\runner.py", line 331, in run_tests
    test(result)
  File "c:\Python26_32\lib\unittest.py", line 300, in __call__
    return self.run(*args, **kwds)
  File "c:\Python26_32\lib\unittest.py", line 282, in run
    result.addFailure(self, self._exc_info())
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\runner.py", line 804, in addFailure
    exc_info)
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\formatter.py", line 348, in test_failure
    self.print_traceback("Failure in test %s" % test, exc_info)
  File "d:\eggs\zope.testrunner-4.4.4-py2.6.egg\zope\testrunner\formatter.py", line 355, in print_traceback
    print(self.format_traceback(exc_info))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 789: ordinal not in range(128)
```

I think zope.testrunner should be prepared to deal with non-UTF-8 locales, by using `.encode(sys.stdout.encoding, 'backslashreplace')` or something like that.

**Comment by mgedmin** [comment]
This happened again: http://winbot.zope.org/builders/z3c.coverage_py_330_win32/builds/7/steps/test/logs/stdio

**Comment by mgedmin** [comment]
A recent example: https://github.com/buildout/buildout/pull/534/checks?check_run_id=1130262907
