### ISSUE TITLE
1 Test failure with Python 3.5

### ISSUE THREAD

**Issue by felixonmars** [zopefoundation/zope.testrunner#30]
The error message `AttributeError: module 'traceback' has no attribute '_iter_chain'` points me to an upstream issue about Python 3.5. Hope this helps.

FYI: https://bugs.python.org/issue17911

```
Failure in test /build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/tests/testrunner-debugging-layer-setup.test
Failed doctest test for testrunner-debugging-layer-setup.test
  File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/tests/testrunner-debugging-layer-setup.test", line 0

----------------------------------------------------------------------
File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/tests/testrunner-debugging-layer-setup.test", line 104, in testrunner-debugging-layer-setup.test
Failed example:
    try:
        zope.testrunner.run_internal(
          ['--path', dir, '-Dvv', '--tests-pattern', 'tests2'])
    except zope.testrunner.interfaces.EndRun: print("unexpected EndRun!")
    finally: sys.stdin = real_stdin
    # doctest: +ELLIPSIS +REPORT_NDIFF
Differences (ndiff with -expected +actual):
      Running tests at level 1
      Running tests2.Layer1 tests:
        Set up tests2.Layer1 in N.NNN seconds.
        Running:
       a_test (tests2)
        Ran 1 tests with 0 failures, 0 errors and 0 skipped in N.NNN seconds.
      Running tests2.Layer2 tests:
        Tear down tests2.Layer1 ... not supported
        Running in a subprocess.
    -   Set up tests2.Layer2
    +   Set up tests2.Layer2
    ?                       +
      **********************************************************************
      <BLANKLINE>
      Can't post-mortem debug when running a layer as a subprocess!
      Try running layer 'tests2.Layer2' by itself.
      <BLANKLINE>
      **********************************************************************
      <BLANKLINE>
      Traceback (most recent call last):
    - ...
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/runner.py", Line NNN, in run_layer
    +     setup_layer(options, layer, setup_layers)
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/runner.py", Line NNN, in setup_layer
    +     layer.setUp()
    +   File "/tmp/tmpogi85o17/TESTS-DIR/tests2.py", Line NNN, in setUp
          raise ValueError
      ValueError
      <BLANKLINE>
    + During handling of the above exception, another exception occurred:
    + <BLANKLINE>
    + Traceback (most recent call last):
    +   File "/tmp/temprunner40qrn382", Line NNN, in ?
    +     '--test-path', '/build/python-zope-testrunner/src/zope.testrunner/src', '-c'
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/__init__.py", Line NNN, in run
    +     failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd)
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/__init__.py", Line NNN, in run_internal
    +     runner.run()
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/runner.py", Line NNN, in run
    +     self.run_tests()
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/runner.py", Line NNN, in run_tests
    +     self.skipped, self.import_errors)
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/runner.py", Line NNN, in run_layer
    +     traceback.print_exc(file=f)
    +   File "/usr/lib/python3.5/traceback.py", Line NNN, in print_exc
    +     print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
    +   File "/build/python-zope-testrunner/src/zope.testrunner/src/zope/testrunner/tb_format.py", Line NNN, in print_exception
    +     values = traceback._iter_chain(v, tb)
    + AttributeError: module 'traceback' has no attribute '_iter_chain'
    + <BLANKLINE>
    + **********************************************************************
    + Could not communicate with subprocess!
    + Child command line: ['/usr/bin/python', '/tmp/temprunner40qrn382', '--resume-layer', 'tests2.Layer2', '0', '--default', '--path', '--default', '/tmp/tmpogi85o17/TESTS-DIR', '--default', '-Dvv', '--default', '--tests-pattern', '--default', 'tests2']
    + Child stderr was:
    + <BLANKLINE>
    + **********************************************************************
    + <BLANKLINE>
      <BLANKLINE>
      Tests with errors:
    -    Layer: tests2.Layer2
    +    subprocess for tests2.Layer2
      Total: 1 tests, 0 failures, 1 errors and 0 skipped in N.NNN seconds.
      True
```

**Comment by felixonmars** [comment]
Fixed with #31
