### ISSUE TITLE
Python 3.5 test failures on Travis

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.testrunner#47]
`master` has test failures on Travis on Python 3.5:
- https://travis-ci.org/zopefoundation/zope.testrunner/builds/186172365

```
Traceback (most recent call last):
  File "/tmp/temprunner_xdf2ew1", line 10, in <module>
    '--test-path', '/home/travis/build/zopefoundation/zope.testrunner/src', '-c'
  File "/home/travis/build/zopefoundation/zope.testrunner/.tox/py35/lib/python3.5/site-packages/zope/testrunner/__init__.py", line 27, in run
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd)
  File "/home/travis/build/zopefoundation/zope.testrunner/.tox/py35/lib/python3.5/site-packages/zope/testrunner/__init__.py", line 42, in run_internal
    from zope.testrunner.runner import Runner
  File "/home/travis/build/zopefoundation/zope.testrunner/.tox/py35/lib/python3.5/site-packages/zope/testrunner/runner.py", line 49, in <module>
    import zope.testrunner.tb_format
  File "/home/travis/build/zopefoundation/zope.testrunner/.tox/py35/lib/python3.5/site-packages/zope/testrunner/tb_format.py", line 19, in <module>
    import zope.exceptions.exceptionformatter
ImportError: No module named 'zope.exceptions'
ERROR: InvocationError: '/home/travis/build/zopefoundation/zope.testrunner/.tox/py35/bin/python setup.py -q test -q'
```

Last successful build (of the same commit, so some dependency must've broken us):
- https://travis-ci.org/zopefoundation/zope.testrunner/builds/143345836

I cannot reproduce this failure locally on my laptop with `tox -e py35` (I get a different failure in `testrunner-unexpected-success.txt`).

**Comment by mgedmin** [comment]
I _can_ reproduce an error that looks exactly like this one, with any version of Python (well, I only tried 2.7 and 3.5), if I use `tox --develop`.

**Comment by mgedmin** [comment]
I think this has something to do with namespace packages -- a `zope` with a magic `__init__.py` picked from the current working directory (because of the os.chdir in the wrapper script generated by setup.py), and a Python-3.3-style `zope` without any `__init__.py` that is found in .tox/.../site-packages.
